Repository hyperiumjailbreak/client, pull requests merged in 2019-08, with the labels that each got.

#167 CloudRepo.io proxy repository testing
  build.gradle
Labels: size/XS

#169 Attempt updating LWP
  build.gradle
Labels: Category: CI/Tests, Category: Dependencies, Status: In Progress, auto-merge, size/XS

#172 Kotlin conversion
  src/main/java/cc/hyperium/internal/addons/AddonBootstrap.java
  src/main/java/cc/hyperium/internal/addons/Phase.java
  src/main/kotlin/cc/hyperium/internal/addons/AddonBootstrap.kt
  src/main/kotlin/cc/hyperium/internal/addons/AddonMinecraftBootstrap.kt
Labels: Category: Build, Category: Dependencies, Category: Enhancement, Priority: High, Queue: Releases, auto-merge

#173 Speed up CI
  .cirrus.yml
Labels: size/XS
