Repository hyperiumjailbreak/client, pull requests merged in 2019-09, with the labels that each got.

#175 you are an idiot
  src/main/java/cc/hyperium/mixins/gui/MixinGuiIngame.java
Labels: Category: Enhancement, Issue: Bug, Queue: Releases, auto-merge, size/XS

#176 Reverts #172
  src/main/java/cc/hyperium/internal/addons/AddonBootstrap.java
  src/main/kotlin/cc/hyperium/internal/addons/AddonBootstrap.kt
  src/main/kotlin/cc/hyperium/internal/addons/AddonMinecraftBootstrap.kt
Labels: Category: Build, Category: CI/Tests, Category: Dependencies, Category: Enhancement, Errors: ReadableStack, Issue: Bug, Priority: High, Queue: Releases, Queue: Staging, auto-merge

#182 replace netty with hosted version
  build.gradle
  libs/Netty Client.jar
Labels: Auto-Merge

#184 Delete VictoryRoyale.java
  src/main/java/cc/hyperium/config/Category.java
  src/main/java/cc/hyperium/config/Settings.java
  src/main/java/cc/hyperium/mods/HyperiumModIntegration.java
  src/main/java/cc/hyperium/mods/VictoryRoyale.java
  src/main/java/cc/hyperium/mods/autogg/AutoGGListener.java
  src/main/resources/assets/minecraft/textures/material/victoryroyale/victory_royale.png
Labels: Auto-Merge

#186 Make checksums
  .cirrus.yml
  build.gradle
Labels: Auto-Merge, size/S

#190 Add deploy pipeline
  .cirrus.yml
  .github/cloudrepo_deploy.sh
Labels: Auto-Merge, size/S

#193 Remove levelup broadcasts (broken)
  src/main/java/cc/hyperium/config/Settings.java
  src/main/java/cc/hyperium/event/LevelupEvent.java
Labels: Auto-Merge, Category: Configuration, Category: Mods, Issue: Bug, size/S
