Repository hyperiumjailbreak/client, pull requests merged in 2019-05, with the labels that each got.

#99 Remove notification center
  src/main/java/cc/hyperium/Hyperium.java
  src/main/java/cc/hyperium/config/Settings.java
  src/main/java/cc/hyperium/gui/GuiHyperiumCredits.java
  src/main/java/cc/hyperium/gui/GuiHyperiumScreenIngameMenu.java
  src/main/java/cc/hyperium/gui/HyperiumGui.java
  src/main/java/cc/hyperium/gui/NotificationCenter.java
  src/main/java/cc/hyperium/gui/keybinds/GuiKeybinds.java
  src/main/java/cc/hyperium/handlers/handlers/HypixelDetector.java
  src/main/resources/assets/hyperium/lang/en_US.lang
Labels: enhancement

#115 cleanup
  src/main/java/cc/hyperium/mixins/entity/MixinRenderFish.java
  src/main/java/cc/hyperium/mixinsimp/entity/HyperiumRenderFish.java
Labels: auto-merge

#116 Remove dupe option
  src/main/java/cc/hyperium/config/Settings.java
  src/main/resources/assets/hyperium/lang/en_US.lang
Labels: auto-merge

#120 Added Live Player Count
  src/main/java/cc/hyperium/Hyperium.java
  src/main/java/cc/hyperium/gui/GuiHyperiumScreenIngameMenu.java
Labels: High Priority, auto-merge, enhancement

#117 Remove hyperium capes
  src/main/java/cc/hyperium/config/Settings.java
  src/main/java/cc/hyperium/gui/CapesGui.java
  src/main/java/cc/hyperium/gui/hyperium/tabs/SettingsTab.java
  src/main/java/cc/hyperium/handlers/handlers/animation/cape/CapeHandler.java
  src/main/java/cc/hyperium/network/NetworkHandler.java
  src/main/java/cc/hyperium/purchases/PurchaseApi.java
  src/main/resources/assets/hyperium/lang/en_US.lang
Labels: High Priority, auto-merge, enhancement

#123 Looks like this needs to be deleted
  src/main/java/cc/hyperium/mixins/client/renderer/entity/layers/MixinLayerArmorBase.java
  src/main/java/cc/hyperium/mixinsimp/client/renderer/entity/layers/HyperiumLayerArmorBase.java
  src/main/resources/mixins.hyperium.json
Labels: auto-merge

#124 Remove what looks to be unused
  src/main/java/cc/hyperium/Hyperium.java
  src/main/java/cc/hyperium/utils/HyperiumScheduler.java
Labels: auto-merge

#125 Remove unused method parameters
  src/main/java/cc/hyperium/mixins/MixinMinecraft.java
  src/main/java/cc/hyperium/mixinsimp/HyperiumMinecraft.java
Labels: auto-merge, enhancement

#126 Run player count operations async to reduce stress
  src/main/java/cc/hyperium/Hyperium.java
Labels: enhancement

#128 Give Backend calls their own class
  src/main/java/cc/hyperium/Hyperium.java
  src/main/java/rocks/rdil/jailbreak/BackendHandler.java
Labels: auto-merge, enhancement

#129 Remove potentially unused class
  src/main/java/cc/hyperium/gui/carousel/PurchaseCarousel.java
Labels: auto-merge, enhancement

#131 Shorten code
  src/main/java/cc/hyperium/Hyperium.java
  src/main/java/cc/hyperium/gui/GuiHyperiumScreenIngameMenu.java
  src/main/java/rocks/rdil/jailbreak/BackendHandler.java
  src/main/resources/assets/hyperium/lang/en_US.lang
Labels: auto-merge, enhancement

#132 Remove DeobfStack
  build.gradle
Labels: auto-merge, enhancement, size/XS

#134 Update Checker
  src/main/java/cc/hyperium/Hyperium.java
  src/main/java/rocks/rdil/jailbreak/BackendHandler.java
Labels: auto-merge

#136 Remove quests
  src/main/java/cc/hyperium/Hyperium.java
  src/main/java/cc/hyperium/commands/defaults/CommandQuests.java
  src/main/java/cc/hyperium/handlers/HyperiumHandlers.java
  src/main/java/cc/hyperium/handlers/handlers/chat/QuestTrackingChatHandler.java
  src/main/java/cc/hyperium/handlers/handlers/hypixel/HypixelGuiAugmenter.java
  src/main/java/cc/hyperium/handlers/handlers/quests/PlayerQuestsGui.java
  src/main/java/cc/hyperium/handlers/handlers/stats/AbstractHypixelStats.java
  src/main/java/cc/hyperium/handlers/handlers/stats/PlayerStatsGui.java
  src/main/java/cc/hyperium/handlers/handlers/stats/fields/GeneralStats.java
  src/main/java/club/sk1er/website/api/requests/HypixelApiPlayer.java
  src/main/java/net/hypixel/api/GameType.java
  src/main/resources/remoteresources/chat_regex.json
Labels: Low Priority, auto-merge, enhancement

#138 Remove unused imports
  src/main/java/cc/hyperium/Hyperium.java
Labels: auto-merge, enhancement

#140 Remove some unused assets
  src/main/java/cc/hyperium/event/ArrowShootEvent.java
  src/main/java/cc/hyperium/gui/Icons.java
  src/main/resources/assets/minecraft/textures/material/arrow_down.png
Labels: auto-merge

#144 Remove some events
  src/main/java/cc/hyperium/event/PlayerGetCapeEvent.java
  src/main/java/cc/hyperium/event/PlayerGetSkinEvent.java
  src/main/java/cc/hyperium/event/RenderSelectedItemEvent.java
  src/main/java/cc/hyperium/mixins/gui/MixinGuiIngame.java
  src/main/java/cc/hyperium/mixinsimp/entity/HyperiumNetworkPlayerInfo.java
  src/main/java/cc/hyperium/mixinsimp/gui/HyperiumGuiIngame.java
Labels: auto-merge, enhancement

#146 Remove MixinMultiMap
  src/main/java/cc/hyperium/mixins/utils/MixinMultiMap.java
  src/main/resources/mixins.hyperium.json
Labels: auto-merge, enhancement

#147 Delete LivingDeathEvent
  src/main/java/cc/hyperium/event/LivingDeathEvent.java
  src/main/java/cc/hyperium/mixins/entity/MixinEntityLivingBase.java
  src/main/java/cc/hyperium/mixins/entity/MixinEntityPlayer.java
  src/main/java/cc/hyperium/mixins/entity/MixinEntityPlayerMP.java
  src/main/java/cc/hyperium/mixinsimp/entity/HyperiumEntityLivingBase.java
  src/main/java/cc/hyperium/mixinsimp/entity/HyperiumEntityPlayer.java
  src/main/java/cc/hyperium/mixinsimp/entity/HyperiumEntityPlayerMP.java
  src/main/resources/mixins.hyperium.json
Labels: enhancement
